backend:
  name: git-gateway
  branch: main

media_folder: "client/public/attached_assets"
public_folder: "/attached_assets"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "projects"
        label: "Projects"
        file: "client/src/data/projects.json"
        fields:
          - label: "Portfolio Projects"
            name: "projects"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "number", value_type: "int"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image URL", name: "imageUrl", widget: "image"}
              - {label: "Link", name: "link", widget: "string", required: false}
